import React, { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { supabase } from "./supabaseClient";
import { RefreshCw, Bell, Plus, Users, CalendarDays, ListChecks, BarChart3, Home, Save, X, Trash2, MapPin, Upload, Image as ImageIcon, Navigation } from "lucide-react";

const APP_VERSION = "Castan Realtime v1.3.0-etapa2";
const COLORS = ["#B91C1C", "#1E5A8A", "#15803D", "#C05621", "#7E22CE", "#0F766E", "#BE123C", "#2563EB"];
const ROLES = { admin: "ADM", pre_atendimento: "Pré atendimento", mostrador: "Mostrador", fechamento: "Fechamento" };
const STATUS = [["agendada","Agendada"],["confirmada","Confirmada"],["concluida","Concluída"],["nao_apareceu","Não apareceu"],["cancelada","Cancelada"],["remarcada","Remarcada"],["avancou_fechamento","Avançou p/ fechamento"],["contrato","Virou contrato"]];
const MONTHS = ["Janeiro","Fevereiro","Março","Abril","Maio","Junho","Julho","Agosto","Setembro","Outubro","Novembro","Dezembro"];
const WEEKDAYS = ["Dom","Seg","Ter","Qua","Qui","Sex","Sáb"];
const todayISO = () => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`; };
const brMoney = v => Number(v || 0).toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
const brDateTime = v => v ? new Date(v).toLocaleString("pt-BR") : "";
const statusLabel = v => STATUS.find(s => s[0] === v)?.[1] || v || "";
const statusClass = v => `status ${v || "agendada"}`;
const normalizeMoney = v => (v === "" || v === null || v === undefined) ? null : Number(String(v).replace(".", "").replace(",", "."));
const mapLink = (lat,lng) => lat && lng ? `https://www.google.com/maps?q=${lat},${lng}` : "";
const wazeLink = (lat, lng) => {
  if (!lat || !lng) return "";
  return `https://waze.com/ul?ll=${lat},${lng}&navigate=yes`;
};
function exportCsv(filename, rows){ const csv=rows.map(r=>r.map(c=>`"${String(c??"").replaceAll('"','""')}"`).join(";")).join("\n"); const b=new Blob(["\uFEFF"+csv],{type:"text/csv;charset=utf-8"}); const a=document.createElement("a"); a.href=URL.createObjectURL(b); a.download=filename; a.click(); URL.revokeObjectURL(a.href); }
function emptyVisit(user, preUsers, mostradores){ return { id:null,codigo_imovel:"",endereco_imovel:"",proprietario_nome:"",proprietario_contato:"",cliente_nome:"",cliente_contato:"",pre_atendimento_id:user?.tipo==="pre_atendimento"?user.id:(preUsers[0]?.id||""),mostrador_id:mostradores[0]?.id||"",data_visita:todayISO(),horario_visita:"09:00",status:"agendada",observacao:"",checklist:false,valor_proposta:"",contrato_fechado:false,latitude:null,longitude:null,geolocalizacao_data:null}; }

export default function App(){
  const [usuarios,setUsuarios]=useState([]), [visitas,setVisitas]=useState([]), [notificacoes,setNotificacoes]=useState([]), [acoes,setAcoes]=useState([]), [fotos,setFotos]=useState([]);
  const [currentUserId,setCurrentUserId]=useState(localStorage.getItem("castan_logged_user")||"");
  const [loginUserId,setLoginUserId]=useState("");
  const [loginPassword,setLoginPassword]=useState("");
  const [view,setView]=useState("inicio"), [loading,setLoading]=useState(true), [lastSync,setLastSync]=useState(""), [modalVisit,setModalVisit]=useState(null), [modalUser,setModalUser]=useState(null);
  const savedFilters = (()=>{ try{return JSON.parse(localStorage.getItem("castan_saved_filters")||"{}")}catch{return {}} })();
  const [reportDate,setReportDate]=useState(todayISO()), [filterPre,setFilterPre]=useState(savedFilters.filterPre||"all"), [filterMostrador,setFilterMostrador]=useState(savedFilters.filterMostrador||"all"), [filterStatus,setFilterStatus]=useState(savedFilters.filterStatus||"all"), [searchTerm,setSearchTerm]=useState(savedFilters.searchTerm||"");
  const [month,setMonth]=useState(new Date().getMonth()), [year,setYear]=useState(new Date().getFullYear());
  const touchStart=useRef(0);
  const user=usuarios.find(u=>u.id===currentUserId); const isAdmin=user?.tipo==="admin", isPre=user?.tipo==="pre_atendimento", isMostrador=user?.tipo==="mostrador", isFechamento=user?.tipo==="fechamento";
  const preUsers=usuarios.filter(u=>u.tipo==="pre_atendimento"&&u.ativo!==false), mostradores=usuarios.filter(u=>u.tipo==="mostrador"&&u.ativo!==false), fechamentoUsers=usuarios.filter(u=>u.tipo==="fechamento"&&u.ativo!==false);
  const canCreateVisit=isAdmin||isPre, canManageUsers=isAdmin;

  const seedIfEmpty=useCallback(async()=>{ const {data,error}=await supabase.from("usuarios").select("id").limit(1); if(error||data?.length)return; await supabase.from("usuarios").insert([{nome:"Administrador",tipo:"admin",ativo:true},{nome:"Pré Atendimento 1",tipo:"pre_atendimento",ativo:true},{nome:"Pré Atendimento 2",tipo:"pre_atendimento",ativo:true},{nome:"Pré Atendimento 3",tipo:"pre_atendimento",ativo:true},{nome:"Pré Atendimento 4",tipo:"pre_atendimento",ativo:true},{nome:"Mostrador 1",tipo:"mostrador",ativo:true},{nome:"Mostrador 2",tipo:"mostrador",ativo:true},{nome:"Mostrador 3",tipo:"mostrador",ativo:true},{nome:"Fechamento 1",tipo:"fechamento",ativo:true},{nome:"Fechamento 2",tipo:"fechamento",ativo:true},{nome:"Fechamento 3",tipo:"fechamento",ativo:true}]); },[]);
  const loadAll=useCallback(async()=>{ try{ const [u,v,n,a,ft]=await Promise.all([supabase.from("usuarios").select("*").order("created_at",{ascending:true}),supabase.from("visitas").select("*").order("data_visita",{ascending:true}).order("horario_visita",{ascending:true}),supabase.from("notificacoes").select("*").order("created_at",{ascending:false}).limit(200),supabase.from("acoes_visita").select("*").order("created_at",{ascending:false}).limit(500),supabase.from("fotos_visita").select("*").order("created_at",{ascending:false}).limit(500)]); if(!u.error)setUsuarios(u.data||[]); if(!v.error)setVisitas(v.data||[]); if(!n.error)setNotificacoes(n.data||[]); if(!a.error)setAcoes(a.data||[]); if(!ft.error)setFotos(ft.data||[]); setLastSync(new Date().toLocaleTimeString("pt-BR")); } finally{ setLoading(false); } },[]);
  useEffect(()=>{seedIfEmpty().then(loadAll)},[seedIfEmpty,loadAll]);
  useEffect(()=>{if(currentUserId)localStorage.setItem("castan_logged_user",currentUserId);else localStorage.removeItem("castan_logged_user")},[currentUserId]);
  useEffect(()=>{localStorage.setItem("castan_saved_filters",JSON.stringify({filterPre,filterMostrador,filterStatus,searchTerm}))},[filterPre,filterMostrador,filterStatus,searchTerm]);
  useEffect(()=>{ const ch=supabase.channel("castan-realtime-global").on("postgres_changes",{event:"*",schema:"public",table:"usuarios"},loadAll).on("postgres_changes",{event:"*",schema:"public",table:"visitas"},loadAll).on("postgres_changes",{event:"*",schema:"public",table:"notificacoes"},loadAll).on("postgres_changes",{event:"*",schema:"public",table:"acoes_visita"},loadAll).on("postgres_changes",{event:"*",schema:"public",table:"fotos_visita"},loadAll).subscribe(); const interval=setInterval(loadAll,3000); const visibility=()=>{if(!document.hidden)loadAll()}; window.addEventListener("focus",loadAll); document.addEventListener("visibilitychange",visibility); return()=>{supabase.removeChannel(ch);clearInterval(interval);window.removeEventListener("focus",loadAll);document.removeEventListener("visibilitychange",visibility)}; },[loadAll]);

  function getUser(id){return usuarios.find(u=>u.id===id)} function colorForUser(id){const idx=Math.max(0,usuarios.findIndex(u=>u.id===id)); return COLORS[idx%COLORS.length]}
  function canEditVisit(v){ if(isAdmin||isPre||isFechamento)return true; if(isMostrador)return v.mostrador_id===user?.id; return false; }
  async function notifyMany(ids,titulo,mensagem){ const unique=[...new Set((ids||[]).filter(Boolean))]; if(unique.length) await supabase.from("notificacoes").insert(unique.map(usuario_id=>({usuario_id,titulo,mensagem}))); }
  function doLogin(){ const selected=usuarios.find(u=>u.id===loginUserId); if(!selected)return alert("Selecione seu usuário."); if(String(selected.senha||"")!==String(loginPassword||""))return alert("Senha incorreta."); setCurrentUserId(selected.id); setLoginPassword(""); }
  function doLogout(){ setCurrentUserId(""); setLoginUserId(""); setLoginPassword(""); setView("inicio"); }
  async function saveVisit(){ const f={...modalVisit}; if(!f.codigo_imovel||!f.endereco_imovel||!f.proprietario_nome||!f.proprietario_contato||!f.cliente_nome||!f.cliente_contato||!f.pre_atendimento_id||!f.mostrador_id||!f.data_visita||!f.horario_visita)return alert("Preencha todos os campos obrigatórios: imóvel, endereço, proprietário, contatos, cliente, pré atendimento, mostrador, data e horário."); const old=f.id?visitas.find(v=>v.id===f.id):null; if(isMostrador&&f.status!==old?.status&&["concluida","nao_apareceu","cancelada","remarcada"].includes(f.status)&&!String(f.observacao||"").trim())return alert("Para alterar para este status, o mostrador precisa preencher uma observação."); if(isFechamento&&f.checklist&&!normalizeMoney(f.valor_proposta))return alert("Para marcar Check List, o fechamento precisa informar o valor da proposta."); const payload={codigo_imovel:f.codigo_imovel,endereco_imovel:f.endereco_imovel||null,proprietario_nome:f.proprietario_nome||null,proprietario_contato:f.proprietario_contato||null,cliente_nome:f.cliente_nome,cliente_contato:f.cliente_contato||null,pre_atendimento_id:f.pre_atendimento_id,mostrador_id:f.mostrador_id,data_visita:f.data_visita,horario_visita:f.horario_visita,status:f.status||"agendada",observacao:f.observacao||null,checklist:Boolean(f.checklist),valor_proposta:normalizeMoney(f.valor_proposta),contrato_fechado:Boolean(f.contrato_fechado),latitude:f.latitude||null,longitude:f.longitude||null,geolocalizacao_data:f.geolocalizacao_data||null,created_by:f.created_by||user?.id||null};
    if(f.id){ const {error}=await supabase.from("visitas").update(payload).eq("id",f.id); if(error)return alert(error.message); if(old?.status!==payload.status){ await supabase.from("acoes_visita").insert({visita_id:f.id,usuario_id:user?.id,tipo_acao:"alteracao_status",status_anterior:old?.status||null,status_novo:payload.status,observacao:payload.observacao,valor_proposta:payload.valor_proposta}); if(isMostrador&&["nao_apareceu","cancelada","remarcada"].includes(payload.status)) await notifyMany([payload.pre_atendimento_id],"Atualização do mostrador",`${payload.codigo_imovel} - ${payload.cliente_nome}: ${statusLabel(payload.status)}.`); if(payload.status==="concluida") await notifyMany(fechamentoUsers.map(u=>u.id),"Visita concluída",`${payload.codigo_imovel} - ${payload.cliente_nome} foi concluída. Avaliar fechamento.`); } if(!old?.checklist&&payload.checklist){ await supabase.from("acoes_visita").insert({visita_id:f.id,usuario_id:user?.id,tipo_acao:"checklist",status_anterior:old?.status||null,status_novo:payload.status,observacao:payload.observacao,valor_proposta:payload.valor_proposta}); await notifyMany(fechamentoUsers.map(u=>u.id),"Check List acionado",`${payload.codigo_imovel} - ${payload.cliente_nome} entrou em check list.`); } }
    else{ const {data,error}=await supabase.from("visitas").insert(payload).select("*").single(); if(error)return alert(error.message); await supabase.from("acoes_visita").insert({visita_id:data.id,usuario_id:user?.id,tipo_acao:"criacao_visita",status_novo:payload.status,observacao:payload.observacao}); await notifyMany([payload.mostrador_id,payload.pre_atendimento_id],"Nova visita agendada",`${payload.codigo_imovel} - ${payload.cliente_nome} em ${payload.data_visita} às ${String(payload.horario_visita).slice(0,5)}.`); }
    setModalVisit(null); await loadAll(); }
  async function deleteVisit(id){ if(!isAdmin)return alert("Somente o ADM pode excluir visitas."); if(!confirm("Excluir visita?"))return; await supabase.from("visitas").delete().eq("id",id); setModalVisit(null); await loadAll(); }
  async function saveUser(){ const u=modalUser; if(!u.nome||!u.tipo)return alert("Informe nome e perfil."); if(!u.id&&!u.senha)return alert("Informe uma senha inicial para o usuário."); if(u.id) await supabase.from("usuarios").update({nome:u.nome,email:u.email||null,tipo:u.tipo,senha:u.senha||"123456",ativo:u.ativo!==false}).eq("id",u.id); else await supabase.from("usuarios").insert({nome:u.nome,email:u.email||null,tipo:u.tipo,senha:u.senha||"123456",ativo:true}); setModalUser(null); await loadAll(); }
  async function deleteUser(id){ if(!isAdmin)return; if(!confirm("Desativar usuário?"))return; await supabase.from("usuarios").update({ativo:false}).eq("id",id); await loadAll(); }
  function captureLocationForModal(){
    if(!navigator.geolocation) return alert("Geolocalização não disponível neste aparelho.");
    navigator.geolocation.getCurrentPosition(pos=>{
      setModalVisit(f=>({...f,latitude:pos.coords.latitude,longitude:pos.coords.longitude,geolocalizacao_data:new Date().toISOString()}));
      alert("Localização capturada com sucesso.");
    },()=>alert("Não foi possível capturar a localização. Verifique a permissão do navegador."),{enableHighAccuracy:true,timeout:12000});
  }
  async function uploadVisitFiles(files){
    if(!modalVisit?.id) return alert("Salve a visita antes de anexar fotos/checklist.");
    const list=Array.from(files||[]);
    if(!list.length)return;
    for(const file of list){
      const safeName=file.name.normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-zA-Z0-9._-]/g,"-");
      const path=`visitas/${modalVisit.id}/${Date.now()}-${safeName}`;
      const up=await supabase.storage.from("visita-fotos").upload(path,file,{upsert:false});
      if(up.error){ alert(up.error.message); continue; }
      const pub=supabase.storage.from("visita-fotos").getPublicUrl(path);
      await supabase.from("fotos_visita").insert({visita_id:modalVisit.id,usuario_id:user?.id,nome_arquivo:file.name,tipo_arquivo:file.type,url_arquivo:pub.data.publicUrl,caminho_arquivo:path});
      await supabase.from("acoes_visita").insert({visita_id:modalVisit.id,usuario_id:user?.id,tipo_acao:"upload_foto_checklist",observacao:`Arquivo anexado: ${file.name}`});
    }
    await loadAll();
    alert("Arquivo(s) anexado(s) com sucesso.");
  }

  const visibleVisits=useMemo(()=>{ const q=String(searchTerm||"").toLowerCase().trim(); return visitas.filter(v=>{ const byPre=filterPre==="all"||v.pre_atendimento_id===filterPre; const byMostrador=filterMostrador==="all"||v.mostrador_id===filterMostrador; const byStatus=filterStatus==="all"||v.status===filterStatus; const haystack=[v.codigo_imovel,v.endereco_imovel,v.cliente_nome,v.cliente_contato,v.proprietario_nome,v.proprietario_contato,statusLabel(v.status),getUser(v.pre_atendimento_id)?.nome,getUser(v.mostrador_id)?.nome].join(" ").toLowerCase(); const bySearch=!q||haystack.includes(q); return byPre&&byMostrador&&byStatus&&bySearch; }); },[visitas,filterPre,filterMostrador,filterStatus,searchTerm,usuarios]);
  const todayVisits=visibleVisits.filter(v=>v.data_visita===todayISO()).sort((a,b)=>String(a.horario_visita).localeCompare(String(b.horario_visita))); const reportVisits=visitas.filter(v=>v.data_visita===reportDate);
  const buildReport=arr=>({visitas:arr.length,concluidas:arr.filter(v=>["concluida","avancou_fechamento","contrato"].includes(v.status)).length,desmarcadas:arr.filter(v=>["cancelada","nao_apareceu"].includes(v.status)).length,fechamento:arr.filter(v=>v.checklist||v.status==="avancou_fechamento"||v.status==="contrato").length,contratos:arr.filter(v=>v.contrato_fechado||v.status==="contrato").length,valor:arr.reduce((s,v)=>s+Number(v.valor_proposta||0),0)});
  const reportByPre=preUsers.map(p=>({nome:p.nome,...buildReport(reportVisits.filter(v=>v.pre_atendimento_id===p.id))})); const reportByMostrador=mostradores.map(m=>({nome:m.nome,...buildReport(reportVisits.filter(v=>v.mostrador_id===m.id))}));
  const statusResumo=STATUS.map(([id,label])=>({id,label,total:visitas.filter(v=>v.status===id).length})).filter(x=>x.total>0);
  const rankingPre=preUsers.map(p=>({nome:p.nome,total:visitas.filter(v=>v.pre_atendimento_id===p.id).length})).sort((a,b)=>b.total-a.total);
  const minhaAgendaVisits=visitas.filter(v=>isMostrador?v.mostrador_id===user?.id:true).sort((a,b)=>(a.data_visita+String(a.horario_visita)).localeCompare(b.data_visita+String(b.horario_visita)));
  function exportReport(){ const rows=[["Tipo","Nome","Visitas","Concluídas","Desmarcadas/Não apareceu","Avançaram fechamento","Contratos","Valor propostas"]]; reportByPre.forEach(r=>rows.push(["Pré atendimento",r.nome,r.visitas,r.concluidas,r.desmarcadas,r.fechamento,r.contratos,brMoney(r.valor)])); reportByMostrador.forEach(r=>rows.push(["Mostrador",r.nome,r.visitas,r.concluidas,r.desmarcadas,r.fechamento,r.contratos,brMoney(r.valor)])); rows.push([],["Ações do mostrador/fechamento"],["Horário","Usuário","Ação","Imóvel","Cliente","Status anterior","Status novo","Valor proposta","Observação"]); acoes.filter(a=>visitas.find(x=>x.id===a.visita_id)?.data_visita===reportDate).forEach(a=>{const v=visitas.find(x=>x.id===a.visita_id); rows.push([brDateTime(a.created_at),getUser(a.usuario_id)?.nome||"",a.tipo_acao,v?.codigo_imovel||"",v?.cliente_nome||"",statusLabel(a.status_anterior),statusLabel(a.status_novo),brMoney(a.valor_proposta),a.observacao||""])}); exportCsv(`castan-relatorio-${reportDate}.csv`,rows); }
  function startNewVisit(day=null){ if(!canCreateVisit)return alert("Seu perfil não pode criar visitas."); setModalVisit({...emptyVisit(user,preUsers,mostradores),data_visita:day||todayISO()}); }
  function openVisit(v){ if(!canEditVisit(v))return alert("Você pode visualizar, mas não pode editar esta visita."); setModalVisit({...v,valor_proposta:v.valor_proposta||""}); }
  const unread=notificacoes.filter(n=>n.usuario_id===user?.id&&!n.lida).length;
  if(loading)return <div className="loading">Carregando Castan Visitas...</div>;
  return <div className="app" onTouchStart={e=>{touchStart.current=e.touches[0].clientY}} onTouchEnd={e=>{const end=e.changedTouches[0].clientY;if(window.scrollY===0&&end-touchStart.current>80)loadAll()}}>
    <header className="header"><div><h1>Castan Visitas</h1><p>Agenda operacional realtime — {APP_VERSION}</p></div><div className="header-actions">{user&&<div className="notif">{user.nome} — {ROLES[user.tipo]}</div>}<button onClick={loadAll} className="btn ghost"><RefreshCw size={16}/> Atualizar</button>{user&&<div className="notif"><Bell size={16}/> {unread}</div>}{canCreateVisit&&<button className="btn primary" onClick={()=>startNewVisit()}><Plus size={16}/> Nova Visita</button>}{user&&<button className="btn ghost" onClick={doLogout}>Sair</button>}</div></header>
    {!user?<main className="select-user"><h2>Entrar no Castan Visitas</h2><p>Selecione seu usuário e informe sua senha.</p><div className="loginbox"><select value={loginUserId} onChange={e=>setLoginUserId(e.target.value)}><option value="">Selecione o usuário</option>{usuarios.filter(u=>u.ativo!==false).map(u=><option key={u.id} value={u.id}>{u.nome} — {ROLES[u.tipo]}</option>)}</select><input type="password" value={loginPassword} onChange={e=>setLoginPassword(e.target.value)} placeholder="Senha" onKeyDown={e=>{if(e.key==="Enter")doLogin()}}/><button className="btn primary" onClick={doLogin}>Entrar</button></div><p className="hint">Senha inicial padrão: 123456. O ADM pode alterar a senha na aba Equipe.</p></main>:<><nav className="tabs">{[["inicio",Home,"Inicial"],["calendario",CalendarDays,"Calendário"],["minha_agenda",CalendarDays,"Minha agenda"],["lista",ListChecks,"Lista"],["relatorios",BarChart3,"Relatórios"],["equipe",Users,"Equipe"]].map(([id,Icon,label])=><button key={id} onClick={()=>setView(id)} className={view===id?"active":""}><Icon size={16}/> {label}</button>)}</nav><main className="content"><div className="sync">Última sincronização: {lastSync}</div>
      {view==="inicio"&&<><section className="metrics"><Metric title="Visitas do dia" value={todayVisits.length}/><Metric title="Agendadas" value={todayVisits.filter(v=>["agendada","confirmada"].includes(v.status)).length}/><Metric title="Canceladas" value={todayVisits.filter(v=>v.status==="cancelada").length}/><Metric title="Remarcadas" value={todayVisits.filter(v=>v.status==="remarcada").length}/><Metric title="Equipe" value={usuarios.filter(u=>u.ativo!==false).length}/></section><section className="grid2"><Card title="Visitas de hoje">{todayVisits.map(v=><VisitCard key={v.id} v={v} getUser={getUser} colorForUser={colorForUser} onClick={()=>openVisit(v)}/>)}{!todayVisits.length&&<Empty text="Nenhuma visita para hoje."/>}</Card><Card title="Notificações">{notificacoes.filter(n=>n.usuario_id===user.id).slice(0,12).map(n=><div className="notification" key={n.id}><strong>{n.titulo}</strong><p>{n.mensagem}</p><small>{brDateTime(n.created_at)}</small></div>)}{!notificacoes.filter(n=>n.usuario_id===user.id).length&&<Empty text="Nenhuma notificação."/>}</Card></section><section className="grid2"><Card title="Dashboard por status"><SimpleBars rows={statusResumo}/></Card><Card title="Ranking Pré-atendimento"><SimpleBars rows={rankingPre}/></Card></section></>}
      {view==="calendario"&&<><Filters preUsers={preUsers} mostradores={mostradores} filterPre={filterPre} setFilterPre={setFilterPre} filterMostrador={filterMostrador} setFilterMostrador={setFilterMostrador} filterStatus={filterStatus} setFilterStatus={setFilterStatus} searchTerm={searchTerm} setSearchTerm={setSearchTerm}/><Card><div className="monthbar"><button onClick={()=>{const m=month-1;if(m<0){setMonth(11);setYear(year-1)}else setMonth(m)}}>‹</button><strong>{MONTHS[month]} {year}</strong><button onClick={()=>{const m=month+1;if(m>11){setMonth(0);setYear(year+1)}else setMonth(m)}}>›</button></div><Calendar year={year} month={month} visitas={visibleVisits} colorForUser={colorForUser} onNew={startNewVisit} onEdit={openVisit}/></Card></>}
      {view==="minha_agenda"&&<Card title={isMostrador?"Minha agenda de visitas":"Agenda dos mostradores"}>{minhaAgendaVisits.map(v=><VisitCard key={v.id} v={v} getUser={getUser} colorForUser={colorForUser} onClick={()=>openVisit(v)}/>)}{!minhaAgendaVisits.length&&<Empty text="Nenhuma visita encontrada para esta agenda."/>}</Card>}
      {view==="lista"&&<><Filters preUsers={preUsers} mostradores={mostradores} filterPre={filterPre} setFilterPre={setFilterPre} filterMostrador={filterMostrador} setFilterMostrador={setFilterMostrador} filterStatus={filterStatus} setFilterStatus={setFilterStatus} searchTerm={searchTerm} setSearchTerm={setSearchTerm}/><Card title="Lista de visitas">{visibleVisits.map(v=><VisitCard key={v.id} v={v} getUser={getUser} colorForUser={colorForUser} onClick={()=>openVisit(v)}/>)}</Card></>}
      {view==="relatorios"&&<Card title="Relatórios"><div className="reportbar"><input type="date" value={reportDate} onChange={e=>setReportDate(e.target.value)}/><button className="btn primary" onClick={exportReport}>Exportar CSV/Excel</button></div><h3>Por pré-atendimento</h3><ReportTable rows={reportByPre}/><h3>Por mostrador</h3><ReportTable rows={reportByMostrador}/><h3>Horário das ações</h3><ActionTable acoes={acoes} visitas={visitas} getUser={getUser} reportDate={reportDate}/></Card>}
      {view==="equipe"&&<Card title="Equipe">{canManageUsers&&<button className="btn primary" onClick={()=>setModalUser({nome:"",email:"",tipo:"pre_atendimento",senha:"123456",ativo:true})}><Plus size={16}/> Novo usuário</button>}<div className="teamgrid">{usuarios.filter(u=>u.ativo!==false).map(u=><div className="teamcard" key={u.id}><strong>{u.nome}</strong><span>{ROLES[u.tipo]}</span>{canManageUsers&&<div><button onClick={()=>setModalUser(u)} className="btn ghost">Editar</button><button onClick={()=>deleteUser(u.id)} className="btn danger">Desativar</button></div>}</div>)}</div></Card>}
    </main></>}
    {modalVisit&&<VisitModal f={modalVisit} setF={setModalVisit} onClose={()=>setModalVisit(null)} onSave={saveVisit} onDelete={deleteVisit} isAdmin={isAdmin} isMostrador={isMostrador} isFechamento={isFechamento} preUsers={preUsers} mostradores={mostradores} editing={!!modalVisit.id} acoes={acoes} fotos={fotos} getUser={getUser} onCaptureLocation={captureLocationForModal} onUploadFiles={uploadVisitFiles}/>} {modalUser&&<UserModal u={modalUser} setU={setModalUser} onClose={()=>setModalUser(null)} onSave={saveUser}/>} </div>;
}
function SimpleBars({rows}){ const max=Math.max(1,...rows.map(r=>r.total||0)); return <div>{rows.length?rows.map(r=><div key={r.id||r.nome} style={{marginBottom:10}}><div style={{display:"flex",justifyContent:"space-between",fontSize:13,fontWeight:800}}><span>{r.label||r.nome}</span><span>{r.total}</span></div><div style={{height:10,background:"#E2E8F0",borderRadius:999,overflow:"hidden"}}><div style={{height:"100%",width:`${Math.max(5,(r.total/max)*100)}%`,background:"#123B63"}}/></div></div>):<Empty text="Sem dados para exibir."/>}</div>}
function Metric({title,value}){return <div className="metric"><strong>{value}</strong><span>{title}</span></div>} function Card({title,children}){return <section className="card">{title&&<h2>{title}</h2>}{children}</section>} function Empty({text}){return <div className="empty">{text}</div>}
function Filters({preUsers,mostradores,filterPre,setFilterPre,filterMostrador,setFilterMostrador,filterStatus,setFilterStatus,searchTerm,setSearchTerm}){return <div className="filters"><input placeholder="Buscar imóvel, cliente, proprietário ou contato" value={searchTerm||""} onChange={e=>setSearchTerm(e.target.value)} style={{minWidth:260}}/><select value={filterPre} onChange={e=>setFilterPre(e.target.value)}><option value="all">Todos pré-atendimentos</option>{preUsers.map(u=><option key={u.id} value={u.id}>{u.nome}</option>)}</select><select value={filterMostrador} onChange={e=>setFilterMostrador(e.target.value)}><option value="all">Todos mostradores</option>{mostradores.map(u=><option key={u.id} value={u.id}>{u.nome}</option>)}</select><select value={filterStatus} onChange={e=>setFilterStatus(e.target.value)}><option value="all">Todos status</option>{STATUS.map(s=><option key={s[0]} value={s[0]}>{s[1]}</option>)}</select></div>}
function VisitCard({v,getUser,colorForUser,onClick}){
  return (
    <div className="visitcard" style={{borderLeftColor:colorForUser(v.mostrador_id)}} onClick={onClick}>
      <div>
        <strong>{String(v.horario_visita||"").slice(0,5)} • {v.codigo_imovel} — {v.cliente_nome}</strong>
        <p>Endereço: {v.endereco_imovel||"-"}</p>
        <p>Pré: {getUser(v.pre_atendimento_id)?.nome||"-"} | Mostrador: {getUser(v.mostrador_id)?.nome||"-"}</p>
        <p>Cliente: {v.cliente_contato||"-"} | PP: {v.proprietario_nome||"-"}</p>
        {v.observacao && <p>Obs.: {v.observacao}</p>}

        {v.latitude && v.longitude && (
          <p>
            <a
              href={wazeLink(v.latitude, v.longitude)}
              target="_blank"
              rel="noreferrer"
              onClick={e => e.stopPropagation()}
              className="waze-link"
            >
              Abrir no Waze
            </a>
          </p>
        )}
      </div>

      <div className="badges">
        <span className={statusClass(v.status)}>{statusLabel(v.status)}</span>
        {v.checklist && <span className="status checklist">Check list</span>}
        {v.valor_proposta ? <span className="status valor">{brMoney(v.valor_proposta)}</span> : null}
      </div>
    </div>
  );
}
function Calendar({year,month,visitas,colorForUser,onNew,onEdit}){const first=new Date(year,month,1).getDay(),days=new Date(year,month+1,0).getDate();return <><div className="weekdays">{WEEKDAYS.map(d=><div key={d}>{d}</div>)}</div><div className="calendar">{Array.from({length:first}).map((_,i)=><div className="day emptyday" key={`e${i}`}/>)}{Array.from({length:days}).map((_,i)=>{const day=i+1,date=`${year}-${String(month+1).padStart(2,"0")}-${String(day).padStart(2,"0")}`,arr=visitas.filter(v=>v.data_visita===date);return <div className="day" key={day} onClick={()=>onNew(date)}><b>{day}</b>{arr.slice(0,4).map(v=><div className="chip" key={v.id} style={{background:colorForUser(v.mostrador_id)}} onClick={e=>{e.stopPropagation();onEdit(v)}}>{String(v.horario_visita).slice(0,5)} {v.codigo_imovel}</div>)}{arr.length>4&&<small>+{arr.length-4}</small>}</div>})}</div></>}
function ReportTable({rows}){return <div className="tablewrap"><table><thead><tr><th>Nome</th><th>Visitas</th><th>Concluídas</th><th>Desmarcadas</th><th>Fechamento</th><th>Contratos</th><th>Valor</th></tr></thead><tbody>{rows.map(r=><tr key={r.nome}><td>{r.nome}</td><td>{r.visitas}</td><td>{r.concluidas}</td><td>{r.desmarcadas}</td><td>{r.fechamento}</td><td>{r.contratos}</td><td>{brMoney(r.valor)}</td></tr>)}</tbody></table></div>}
function ActionTable({acoes,visitas,getUser,reportDate}){const rows=acoes.filter(a=>visitas.find(v=>v.id===a.visita_id)?.data_visita===reportDate);return <div className="tablewrap"><table><thead><tr><th>Horário</th><th>Usuário</th><th>Ação</th><th>Imóvel</th><th>Status</th><th>Valor</th><th>Obs.</th></tr></thead><tbody>{rows.map(a=>{const v=visitas.find(x=>x.id===a.visita_id);return <tr key={a.id}><td>{brDateTime(a.created_at)}</td><td>{getUser(a.usuario_id)?.nome||"-"}</td><td>{a.tipo_acao}</td><td>{v?.codigo_imovel}</td><td>{statusLabel(a.status_anterior)} → {statusLabel(a.status_novo)}</td><td>{brMoney(a.valor_proposta)}</td><td>{a.observacao}</td></tr>})}</tbody></table></div>}
function VisitModal({f,setF,onClose,onSave,onDelete,isAdmin,isMostrador,isFechamento,preUsers,mostradores,editing,acoes=[],fotos=[],getUser,onCaptureLocation,onUploadFiles}){
const limited=isMostrador&&!isAdmin; const historico=(acoes||[]).filter(a=>a.visita_id===f.id); const visitFotos=(fotos||[]).filter(x=>x.visita_id===f.id);
return <div className="overlay" onClick={e=>e.target===e.currentTarget&&onClose()}><div className="modal"><div className="modalhead"><h2>{editing?"Editar visita":"Nova visita"}</h2><button onClick={onClose}><X/></button></div><div className="form"><Field label="Código do imóvel *" value={f.codigo_imovel} disabled={limited} onChange={v=>setF({...f,codigo_imovel:v})}/><Field label="Endereço do imóvel *" value={f.endereco_imovel} disabled={limited} onChange={v=>setF({...f,endereco_imovel:v})}/><Field label="Nome do proprietário *" value={f.proprietario_nome} disabled={limited} onChange={v=>setF({...f,proprietario_nome:v})}/><Field label="Contato do proprietário *" value={f.proprietario_contato} disabled={limited} onChange={v=>setF({...f,proprietario_contato:v})}/><Field label="Nome do cliente *" value={f.cliente_nome} disabled={limited} onChange={v=>setF({...f,cliente_nome:v})}/><Field label="Contato do cliente *" value={f.cliente_contato} disabled={limited} onChange={v=>setF({...f,cliente_contato:v})}/><Select label="Pré atendimento *" value={f.pre_atendimento_id} disabled={limited} onChange={v=>setF({...f,pre_atendimento_id:v})} options={preUsers.map(u=>[u.id,u.nome])}/><Select label="Mostrador *" value={f.mostrador_id} disabled={limited} onChange={v=>setF({...f,mostrador_id:v})} options={mostradores.map(u=>[u.id,u.nome])}/><Field label="Data *" type="date" value={f.data_visita} disabled={limited} onChange={v=>setF({...f,data_visita:v})}/><Field label="Horário *" type="time" value={String(f.horario_visita||"").slice(0,5)} disabled={limited} onChange={v=>setF({...f,horario_visita:v})}/><Select label="Status *" value={f.status} onChange={v=>setF({...f,status:v})} options={STATUS}/>{isFechamento&&<label className="check"><input type="checkbox" checked={!!f.checklist} onChange={e=>setF({...f,checklist:e.target.checked,status:e.target.checked?"avancou_fechamento":f.status})}/> Check list / enviar para contrato</label>}{isFechamento&&<Field label="Valor da proposta *" type="number" value={f.valor_proposta||""} onChange={v=>setF({...f,valor_proposta:v})}/>} {isFechamento&&<label className="check"><input type="checkbox" checked={!!f.contrato_fechado} onChange={e=>setF({...f,contrato_fechado:e.target.checked,status:e.target.checked?"contrato":f.status})}/> Virou contrato</label>}<label className="full"><span>Observação {isMostrador?"(obrigatória para concluir/cancelar/remarcar/não apareceu)":""}</span><textarea value={f.observacao||""} onChange={e=>setF({...f,observacao:e.target.value})}/></label></div>
{editing&&<div style={{marginTop:16}}><h3><MapPin size={17}/> Geolocalização da visita</h3><div className="notification"><p>{f.latitude&&f.longitude?`Localização capturada em ${f.geolocalizacao_data?brDateTime(f.geolocalizacao_data):"data não registrada"}`:"Nenhuma localização capturada."}</p>{f.latitude&&f.longitude&&<p><a href={mapLink(f.latitude,f.longitude)} target="_blank" rel="noreferrer">Abrir no Google Maps</a></p>}{f.latitude&&f.longitude&&<p><a href={wazeLink(f.latitude,f.longitude)} target="_blank" rel="noreferrer" className="waze-link">Abrir no Waze</a></p>}<button className="btn ghost" onClick={onCaptureLocation}><Navigation size={16}/> Capturar localização atual</button></div></div>}
{editing&&<div style={{marginTop:16}}><h3><ImageIcon size={17}/> Fotos e checklist</h3><div className="notification"><label className="btn ghost" style={{display:"inline-flex",cursor:"pointer"}}><Upload size={16}/> Anexar fotos/checklist<input type="file" accept="image/*,.pdf" multiple style={{display:"none"}} onChange={e=>onUploadFiles(e.target.files)}/></label><p style={{fontSize:12,color:"#64748B"}}>Use para fotos da visita, comprovantes e checklist em PDF/imagem.</p></div>{visitFotos.length?visitFotos.map(img=><div key={img.id} className="notification"><strong>{img.nome_arquivo}</strong><p>{brDateTime(img.created_at)} — {getUser?.(img.usuario_id)?.nome||"Usuário"}</p>{String(img.tipo_arquivo||"").startsWith("image/")?<a href={img.url_arquivo} target="_blank" rel="noreferrer"><img src={img.url_arquivo} alt={img.nome_arquivo} style={{maxWidth:"180px",borderRadius:10,border:"1px solid #E2E8F0"}}/></a>:<a href={img.url_arquivo} target="_blank" rel="noreferrer">Abrir arquivo</a>}</div>):<Empty text="Nenhum arquivo anexado."/>}</div>}
{editing&&<div style={{marginTop:16}}><h3>Histórico da visita</h3>{historico.length?historico.map(a=><div key={a.id} className="notification"><strong>{brDateTime(a.created_at)} — {getUser?.(a.usuario_id)?.nome||"Usuário"}</strong><p>{a.tipo_acao}: {statusLabel(a.status_anterior)} → {statusLabel(a.status_novo)}</p>{a.observacao&&<p>Obs.: {a.observacao}</p>}{a.valor_proposta&&<small>Valor: {brMoney(a.valor_proposta)}</small>}</div>):<Empty text="Nenhum histórico registrado."/>}</div>}<div className="modalactions">{editing&&isAdmin&&<button className="btn danger" onClick={()=>onDelete(f.id)}><Trash2 size={16}/> Excluir</button>}<button className="btn ghost" onClick={onClose}>Cancelar</button><button className="btn primary" onClick={onSave}><Save size={16}/> Salvar</button></div></div></div>}
function UserModal({u,setU,onClose,onSave}){return <div className="overlay" onClick={e=>e.target===e.currentTarget&&onClose()}><div className="modal smallmodal"><div className="modalhead"><h2>{u.id?"Editar usuário":"Novo usuário"}</h2><button onClick={onClose}><X/></button></div><Field label="Nome *" value={u.nome} onChange={v=>setU({...u,nome:v})}/><Field label="E-mail" value={u.email} onChange={v=>setU({...u,email:v})}/><Field label="Senha *" type="password" value={u.senha||""} onChange={v=>setU({...u,senha:v})}/><Select label="Perfil *" value={u.tipo} onChange={v=>setU({...u,tipo:v})} options={Object.entries(ROLES).map(([k,v])=>[k,v])}/><div className="modalactions"><button className="btn ghost" onClick={onClose}>Cancelar</button><button className="btn primary" onClick={onSave}>Salvar</button></div></div></div>}
function Field({label,value,onChange,type="text",disabled=false}){return <label><span>{label}</span><input type={type} value={value||""} disabled={disabled} onChange={e=>onChange(e.target.value)}/></label>} function Select({label,value,onChange,options,disabled=false}){return <label><span>{label}</span><select value={value||""} disabled={disabled} onChange={e=>onChange(e.target.value)}><option value="">Selecione...</option>{options.map(o=><option key={o[0]} value={o[0]}>{o[1]}</option>)}</select></label>}
